apiVersion: v1
kind: policy
spec:
  name: Password requires 10 or more characters (macOS)
  query: SELECT 1 FROM (SELECT cast(lengthtxt as integer(2)) minlength FROM (SELECT SUBSTRING(length, 1, 2) AS lengthtxt FROM (SELECT policy_description, policy_identifier, split(policy_content, '{', 1) AS length FROM password_policy WHERE policy_identifier LIKE '%minLength')) WHERE minlength >= 10);
  description: "Checks that the password policy requires at least 10 characters. Requires osquery 5.4.0 or newer."
  resolution: "Contact your IT administrator to make sure your Mac is receiving configuration profiles for password length."
  platform: darwin
  tags: compliance, hardening, built-in, CIS, CIS5.2.2
  contributors: GuillaumeRoss