---
apiVersion: v1
kind: policy
spec:
  name: Ensure 'Minimum password length' is set to '14 or more characters'
  platforms: win10
  platform: windows
  description: |
    This policy setting determines the least number of characters that make up a password for a user account.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the following UI path to 14 or more characters
    'Computer Configuration\Policies\Windows Settings\Security Settings\Account Policies\Password Policy\Minimum password length'
  query: |
    SELECT 1 FROM security_profile_info WHERE minimum_password_length >= 14;
  purpose: Informational
  tags: compliance, CIS, CIS_Level1, premium
  contributors: marcosd4h
---
apiVersion: v1
kind: policy
spec:
  name: Full disk encryption enabled (Windows)
  query: SELECT 1 FROM bitlocker_info WHERE drive_letter='C:' AND protection_status=1;
  description: Checks to make sure that full disk encryption is enabled on Windows devices.
  resolution:
    "To get additional information, run the following osquery query on the failing device: SELECT * FROM bitlocker_info. In the
    query results, if protection_status is 2, then the status cannot be determined. If it is 0, it is
    considered unprotected. Use the additional results (percent_encrypted, conversion_status, etc.) to
    help narrow down the specific reason why Windows considers the volume unprotected."
  platform: windows
  tags: compliance, hardening, built-in, critical
  contributors: defensivedepth
---
apiVersion: v1
kind: policy
spec:
  name: Full disk encryption enabled (macOS)
  query: SELECT 1 FROM disk_encryption WHERE user_uuid IS NOT "" AND filevault_status = 'on' LIMIT 1;
  description: Checks to make sure that full disk encryption (FileVault) is enabled on macOS devices.
  resolution: To enable full disk encryption, on the failing device, select System Preferences > Security & Privacy > FileVault > Turn On FileVault.
  tags: compliance, hardening, built-in, CIS, CIS2.5.1.1, critical
  platform: darwin
  contributors: groob
---
apiVersion: v1
kind: policy
spec:
  name: Full disk encryption enabled (Linux)
  query: SELECT 1 FROM mounts m, disk_encryption d WHERE m.device_alias = d.name AND d.encrypted = 1 AND m.path = '/';
  description: Checks if the root drive is encrypted. There are many ways to encrypt Linux systems. This is the default on distributions such as Ubuntu.
  resolution: "Ensure the image deployed to your Linux workstation includes full disk encryption."
  platform: linux
  tags: compliance, hardening, built-in, critical
  contributors: jbilling,GuillaumeRoss
---
apiVersion: v1
kind: policy
spec:
  name: System Integrity Protection enabled (macOS)
  query: SELECT 1 FROM sip_config WHERE config_flag = 'sip' AND enabled = 1;
  description: Checks to make sure that the System Integrity Protection feature is enabled.
  resolution: "To enable System Integrity Protection, on the failing device, run the following command in the Terminal app: /usr/sbin/spctl --master-enable."
  tags: compliance, malware, hardening, built-in, CIS, CIS5.1.2
  platform: darwin
  contributors: groob
---
apiVersion: v1
kind: policy
spec:
  name: Antivirus healthy (Windows)
  query: SELECT 1 from windows_security_center wsc CROSS JOIN windows_security_products wsp WHERE antivirus = 'Good' AND type = 'Antivirus' AND signatures_up_to_date=1;
  description: Checks the status of antivirus and signature updates from the Windows Security Center.
  resolution: "Ensure Windows Defender or your third-party antivirus is running, up to date, and visible in the Windows Security Center."
  tags: compliance, malware, hardening, built-in
  platform: windows
  contributors: GuillaumeRoss
---
apiVersion: v1
kind: policy
spec:
  name: Antivirus healthy (Linux)
  query: SELECT score FROM (SELECT case when COUNT(*) = 2 then 1 ELSE 0 END AS score FROM processes WHERE (name = 'clamd') OR (name = 'freshclam')) WHERE score == 1;
  description: Checks that both ClamAV's daemon and its updater service (freshclam) are running.
  resolution: "Ensure ClamAV and Freshclam are installed and running."
  tags: compliance, malware, hardening, built-in
  platform: linux
  contributors: GuillaumeRoss
---
apiVersion: v1
kind: policy
spec:
  name: MDM enrolled (macOS)
  query: SELECT 1 from mdm WHERE enrolled='true';
  description: "Required: osquery deployed with Orbit, or manual installation of macadmins/osquery-extension. Checks that a mac is enrolled to MDM. Add a AND on identity_certificate_uuid to check for a specific MDM."
  resolution: "Enroll device to MDM"
  tags: compliance, hardening, built-in, critical
  platform: darwin
  contributors: GuillaumeRoss
---
apiVersion: v1
kind: policy
spec:
  name: Docker application is up to date or not present (macOS)
  query: SELECT 1 WHERE EXISTS (SELECT 1 FROM apps a1 WHERE a1.bundle_identifier = 'com.electron.dockerdesktop' AND a1.bundle_short_version>='4.6.1') OR NOT EXISTS (SELECT 1 FROM apps a2 WHERE a2.bundle_identifier = 'com.electron.dockerdesktop');
  description: "Checks if the application (Docker Desktop example) is installed and up to date, or not installed. Fails if the application is installed and on a lower version. You can copy this query and replace the bundle_identifier and bundle_version values to apply the same type of policy to other applications."
  resolution: "Update Docker or remove it if not used."
  tags: inventory, vulnerability, built-in
  platform: darwin
  contributors: GuillaumeRoss
---
apiVersion: v1
kind: policy
spec:
  name: SSH keys encrypted
  query: SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM users CROSS JOIN user_ssh_keys USING (uid) WHERE encrypted='0');
  description: "Required: osquery must have Full Disk Access. Policy passes if all keys are encrypted, including if no keys are present."
  resolution: "Use this command to encrypt existing SSH keys by providing the path to the file: ssh-keygen -o -p -f /path/to/file"
  tags: compliance, ssh, built-in
  contributors: GuillaumeRoss
  platform: darwin,linux,windows
---
apiVersion: v1
kind: policy
spec:
  name: Suspicious autostart (Windows)
  query: SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM startup_items WHERE path = "regsvr32" AND args LIKE "%http%");
  description: "Checks for an autostart that is attempting to load a dynamic link library (DLL) from the internet."
  resolution: "Remove the suspicious startup entry."
  tags: malware, hunting
  platform: windows
  contributors: kswagler-rh
---
apiVersion: v1
kind: policy
spec:
  name: Screen lock enabled (Windows)
  query: SELECT 1 FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\InactivityTimeoutSecs' AND CAST(data as INTEGER) <= 1800;
  description: "Checks if the screen lock is enabled and configured to lock the system within 30 minutes or less."
  resolution: "Contact your IT administrator to enable the Interactive Logon: Machine inactivity limit setting with a value of 1800 seconds or lower."
  tags: compliance, hardening, built-in
  platform: windows
  contributors: GuillaumeRoss
---
apiVersion: v1
kind: policy
spec:
  name: Operating system up to date (macOS)
  query: SELECT 1 FROM os_version WHERE version >= '14.1.1';
  description: "Checks that the operating system is up to date."
  resolution: "From the Apple menu () in the corner of your screen choose System Preferences. Then select Software Update and select Upgrade Now. You might be asked to restart or enter your password."
  tags: compliance, CIS, template, CIS1.1, critical
  platform: darwin
  contributors: GuillaumeRoss
---
apiVersion: v1
kind: policy
spec:
  name: Firewall logging is enabled (macOS)
  query: SELECT 1 FROM managed_policies WHERE domain='com.apple.security.firewall' AND name='EnableLogging' AND value='1' LIMIT 1;
  description: "Checks that a mobile device management (MDM) solution configures the Mac to log firewall activity."
  resolution: "Contact your IT administrator to ensure your Mac is receiving a profile that enables firewall logging."
  tags: MDM required, compliance, CIS, CIS3.6
  platform: darwin
  contributors: GuillaumeRoss
---
apiVersion: v1
kind: policy
spec:
  name: Guest account disabled (macOS)
  query: SELECT 1 FROM managed_policies WHERE domain='com.apple.loginwindow' AND name='DisableGuestAccount' AND value='1' LIMIT 1;
  description: "Checks that a mobile device management (MDM) solution configures the Mac to prevent the use of a guest account."
  resolution: "Contact your IT administrator to ensure your Mac is receiving a profile that disables the guest account."
  tags: MDM required, compliance, CIS, CIS6.1.3
  platform: darwin
  contributors: GuillaumeRoss
---
apiVersion: v1
kind: policy
spec:
  name: Guest access to shared folders is disabled (macOS)
  query: SELECT 1 FROM managed_policies WHERE domain='com.apple.AppleFileServer' AND name='guestAccess' AND value='0' LIMIT 1;
  description: "Checks that a mobile device management (MDM) solution configures the Mac to prevent guest access to shared folders."
  resolution: "Contact your IT administrator to ensure your Mac is receiving a profile that prevents guest access to shared folders."
  tags: MDM required, compliance, CIS, CIS6.1.4
  platform: darwin
  contributors: GuillaumeRoss
---
apiVersion: v1
kind: policy
spec:
  name: No 1Password emergency kit stored in desktop, documents, or downloads folders (macOS)
  query: SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM file WHERE filename LIKE '%Emergency Kit%.pdf' AND (path LIKE '/Users/%/Desktop/%' OR path LIKE '/Users/%/Documents/%' OR path LIKE '/Users/%/Downloads/%' OR path LIKE '/Users/Shared/%'));
  description: "Looks for PDF files with file names typically used by 1Password for emergency recovery kits. To protect the performance of your devices, the search is one level deep and limited to the Desktop, Documents, Downloads, and Shared folders."
  resolution: "Delete 1Password emergency kits from your computer, and empty the trash. 1Password emergency kits should only be printed and stored in a physically secure location."
  platform: darwin
  tags: compliance, built-in
  contributors: nonpunctual
---
apiVersion: v1
kind: policy
spec:
  name: Firewall enabled, domain profile (Windows)
  query: SELECT 1 FROM registry WHERE path LIKE 'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\EnableFirewall' AND CAST(data as integer) = 1;
  description: "Checks if a Group Policy configures the computer to enable the domain profile for Windows Firewall. The domain profile applies to networks where the host system can authenticate to a domain controller. Some auditors requires that this setting is configured by a Group Policy."
  resolution: "Contact your IT administrator to ensure your computer is receiving a Group Policy that enables the domain profile for Windows Firewall."
  platforms: Windows
  tags: compliance, CIS, CIS9.1.1
  platform: windows
  contributors: defensivedepth
---
apiVersion: v1
kind: policy
spec:
  name: Firewall enabled, private profile (Windows)
  query: SELECT 1 FROM registry WHERE path LIKE 'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\EnableFirewall' AND CAST(data as integer) = 1;
  description: "Checks if a Group Policy configures the computer to enable the private profile for Windows Firewall. The private profile applies to networks where the host system is connected to a private or home network. Some auditors requires that this setting is configured by a Group Policy."
  resolution: "Contact your IT administrator to ensure your computer is receiving a Group Policy that enables the private profile for Windows Firewall."
  platforms: Windows
  tags: compliance, CIS, CIS9.2.1
  platform: windows
  contributors: defensivedepth
---
apiVersion: v1
kind: policy
spec:
  name: Firewall enabled, public profile (Windows)
  query: SELECT 1 FROM registry WHERE path LIKE 'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\EnableFirewall' AND CAST(data as integer) = 1;
  description: "Checks if a Group Policy configures the computer to enable the public profile for Windows Firewall. The public profile applies to networks where the host system is connected to public networks such as Wi-Fi hotspots at coffee shops and airports. Some auditors requires that this setting is configured by a Group Policy."
  resolution: "Contact your IT administrator to ensure your computer is receiving a Group Policy that enables the public profile for Windows Firewall."
  platforms: Windows
  tags: compliance, CIS, CIS9.3.1
  platform: windows
  contributors: defensivedepth
---
apiVersion: v1
kind: policy
spec:
  name: SMBv1 client driver disabled (Windows)
  query: SELECT 1 FROM windows_optional_features WHERE name = 'SMB1Protocol-Client' AND state != 1;
  description: "Checks that the SMBv1 client is disabled."
  resolution: "Contact your IT administrator to discuss disabling SMBv1 on your system."
  platforms: Windows
  tags: compliance, CIS, CIS18.3.2, built-in
  platform: windows
  contributors: defensivedepth
---
apiVersion: v1
kind: policy
spec:
  name: SMBv1 server disabled (Windows)
  query: SELECT 1 FROM windows_optional_features WHERE name = 'SMB1Protocol-Server' AND state != 1
  description: "Checks that the SMBv1 server is disabled."
  resolution: "Contact your IT administrator to discuss disabling SMBv1 on your system."
  platforms: Windows
  tags: compliance, CIS, CIS18.3.3, built-in
  platform: windows
  contributors: defensivedepth
---
apiVersion: v1
kind: policy
spec:
  name: Link-Local Multicast Name Resolution (LLMNR) disabled (Windows)
  query: SELECT 1 FROM registry WHERE path LIKE 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\EnableMulticast' AND CAST(data as integer) = 0;
  description: "Checks if a Group Policy configures the computer to disable LLMNR. Disabling LLMNR can prevent malicious actors from gaining access to the computer's credentials. Some auditors require that this setting is configured by a Group Policy."
  resolution: "Contact your IT administrator to ensure your computer is receiving a Group Policy that disables LLMNR on your system."
  platforms: Windows
  tags: compliance, CIS, CIS18.5.4.2
  platform: windows
  contributors: defensivedepth
---
apiVersion: v1
kind: policy
spec:
  name: Automatic updates enabled (Windows)
  query: SELECT 1 FROM registry WHERE path LIKE 'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\WindowsUpdate\AU\NoAutoUpdate' AND CAST(data as integer) = 0;
  description: "Checks if a Group Policy configures the computer to enable Automatic Updates. When enabled, the computer downloads and installs security and other important updates automatically. Some auditors require that this setting is configured by a Group Policy."
  resolution: "Contact your IT administrator to ensure your computer is receiving a Group policy that enables Automatic Updates."
  platforms: Windows
  tags: compliance, CIS, CIS18.9.108.2.1
  platform: windows
  contributors: defensivedepth