apiVersion: v1
kind: policy
spec:
  name: Automatic security and data file updates is enabled (macOS)
  query: SELECT 1 FROM managed_policies WHERE domain='com.apple.SoftwareUpdate' AND name='CriticalUpdateInstall' AND value=1 LIMIT 1;
  description: "Checks that a mobile device management (MDM) solution configures the Mac to automatically download updates to built-in macOS security tools such as malware removal tools."
  resolution: "Contact your IT administrator to ensure your Mac is receiving a profile that enables automatic security and data update installation."
  tags: MDM required, compliance, CIS, CIS1.5
  platform: darwin
  contributors: GuillaumeRoss