apiVersion: v1
kind: policy
spec:
  name: Firewall enabled (macOS)
  query: SELECT 1 FROM alf WHERE global_state >= 1;
  description: "Checks if the firewall is enabled."
  resolution: "In System Preferences, open Security & Privacy, navigate to the Firewall tab and click Turn On Firewall."
  tags: hardening, compliance, built-in, CIS, CIS2.5.2.2
  platform: darwin
  contributors: GuillaumeRoss