apiVersion: v1
kind: policy
spec:
  name: Internet sharing is blocked (macOS)
  query: SELECT 1 FROM managed_policies WHERE domain='com.apple.MCX' AND name='forceInternetSharingOff' AND value='1' LIMIT 1;
  description: "Checks that a mobile device management (MDM) solution configures the Mac to prevent Internet sharing."
  resolution: "Contact your IT administrator to ensure your Mac is receiving a profile that prevents Internet sharing."
  tags: MDM required, compliance, CIS, CIS2.4.2
  platform: darwin
  contributors: GuillaumeRoss