apiVersion: v1
kind: policy
spec:
  name: Ensure 'Minimum password length' is set to '14 or more characters'
  platforms: win10
  platform: windows
  description: |
    This policy setting determines the least number of characters that make up a password for a user account.
  resolution: |
    Automatic method:
    Ask your system administrator to establish the recommended configuration via GP, set the following UI path to 14 or more characters
    'Computer Configuration\Policies\Windows Settings\Security Settings\Account Policies\Password Policy\Minimum password length'
  query: |
    SELECT 1 FROM security_profile_info WHERE minimum_password_length >= 14;
  purpose: Informational
  tags: compliance, CIS, CIS_Level1, premium
  contributors: marcosd4h