apiVersion: v1
kind: policy
spec:
  name: Secure keyboard entry for Terminal application enabled (macOS)
  query: SELECT 1 FROM managed_policies WHERE domain = 'com.apple.Terminal' AND name = 'SecureKeyboardEntry' AND value = 1 LIMIT 1;
  description: "Checks that a mobile device management (MDM) solution configures the Mac to enabled secure keyboard entry for the Terminal application."
  resolution: "Contact your IT administrator to ensure your Mac is receiving a profile that enables secure keyboard entry for the Terminal application."
  tags: MDM required, compliance, hardening, built-in
  platform: darwin
  contributors: groob