apiVersion: v1
kind: policy
spec:
  name: Guest access to shared folders is disabled (macOS)
  query: SELECT 1 FROM managed_policies WHERE domain='com.apple.AppleFileServer' AND name='guestAccess' AND value='0' LIMIT 1;
  description: "Checks that a mobile device management (MDM) solution configures the Mac to prevent guest access to shared folders."
  resolution: "Contact your IT administrator to ensure your Mac is receiving a profile that prevents guest access to shared folders."
  tags: MDM required, compliance, CIS, CIS6.1.4
  platform: darwin
  contributors: GuillaumeRoss