apiVersion: v1
kind: policy
spec:
  name: Automatic installation of operating system updates is enabled (macOS)
  query: SELECT 1 FROM managed_policies WHERE domain='com.apple.SoftwareUpdate' AND name='AutomaticallyInstallMacOSUpdates' AND value=1 LIMIT 1;
  description: "Checks that a mobile device management (MDM) solution configures the Mac to automatically install operating system updates."
  resolution: "Contact your IT administrator to ensure your Mac is receiving a profile that enables automatic installation of operating system updates."
  tags: MDM required, compliance, CIS, CIS1.6
  platform: darwin
  contributors: GuillaumeRoss