apiVersion: v1
kind: policy
spec:
  name: Content caching is disabled (macOS)
  query: SELECT 1 FROM managed_policies WHERE domain='com.apple.applicationaccess' AND name='allowContentCaching' AND value='0' LIMIT 1;
  description: "Checks that a mobile device management (MDM) solution configures the Mac to disable content caching."
  resolution: "Contact your IT administrator to ensure your Mac is receiving a profile that disables content caching."
  tags: MDM required, compliance, CIS, CIS2.4.10
  platform: darwin
  contributors: GuillaumeRoss