apiVersion: v1
kind: policy
spec:
  name: Guest account disabled (macOS)
  query: SELECT 1 FROM managed_policies WHERE domain='com.apple.loginwindow' AND name='DisableGuestAccount' AND value='1' LIMIT 1;
  description: "Checks that a mobile device management (MDM) solution configures the Mac to prevent the use of a guest account."
  resolution: "Contact your IT administrator to ensure your Mac is receiving a profile that disables the guest account."
  tags: MDM required, compliance, CIS, CIS6.1.3
  platform: darwin
  contributors: GuillaumeRoss