apiVersion: v1
kind: policy
spec:
  name: Screen lock enabled (macOS)
  query: SELECT 1 FROM managed_policies WHERE name='askForPassword' AND value='1';
  description: "Checks that a mobile device management (MDM) solution configures the Mac to enable screen lock."
  resolution: "Contact your IT administrator to ensure your Mac is receiving a profile that enables screen lock."
  tags: MDM required, compliance, hardening, built-in
  platform: darwin
  contributors: GuillaumeRoss