apiVersion: v1
kind: policy
spec:
  name: Ensure a password is required to wake the computer from sleep or screen saver is enabled
  platforms: macOS
  platform: darwin
  description: Checks that password is required to wake the computer from sleep or screen saver is enabled.
  resolution: |
    Automated method:
    Ask your system administrator to deploy an MDM profile that ensures a password is required to wake the computer from sleep or screen saver is enabled.
    Graphical method:
      Perform the following steps to ensure a password is required to wake the computer from sleep or screen saver is enabled:
        1. Open System Settings
        2. Select Lock Screen
        3. Verify that "Require password after screensaver begins or display is turned
        off" is set with "After 0 seconds" or "After 5 seconds"
  query: |-
    SELECT 1 WHERE 
      EXISTS (
        SELECT 1 FROM managed_policies WHERE 
            domain='com.apple.screensaver' AND 
            name='askForPassword' AND 
            (value = 1 OR value = 'true') AND 
            username = ''
        )
      AND EXISTS (
        SELECT 1 FROM managed_policies WHERE 
            domain='com.apple.screensaver' AND 
            name='askForPasswordDelay' AND 
            value <= 5 AND 
            username = ''
        )
      AND NOT EXISTS (
        SELECT 1 FROM managed_policies WHERE 
            domain='com.apple.screensaver' AND 
            name='askForPassword' AND 
            (value != 1 AND value != 'true')
        )
      AND NOT EXISTS (
        SELECT 1 FROM managed_policies WHERE 
            domain='com.apple.screensaver' AND 
            name='askForPasswordDelay' AND 
            value > 5
        );  
  purpose: Informational
  tags: compliance, CIS, CIS_Level1, premium,
  contributors: sharon-fdm