apiVersion: v1
kind: policy
spec:
  name: Gatekeeper enabled (macOS)
  query: SELECT 1 FROM gatekeeper WHERE assessments_enabled = 1;
  description: Checks to make sure that the Gatekeeper feature is enabled on macOS devices. Gatekeeper tries to ensure only trusted software is run on a mac machine.
  resolution: "To enable Gatekeeper, on the failing device, run the following command in the Terminal app: /usr/sbin/spctl --master-enable."
  tags: compliance, hardening, built-in, CIS, CIS2.5.2.1, critical
  platform: darwin
  contributors: groob